[tool.mypy]
ignore_missing_imports = true
exclude = [
    "^venv",
    "tests/*"
    ]

[tool.pytest.ini_options]
pythonpath = [
    "source",
]

[tool.ruff]
include = [     # What directories are to be checked
    "source/*.py",
    "tests/*.py",
    "**/pyproject.toml",
]
select = [
    "ALL"   # Use all possible rules
]
ignore = [
    "ANN101",   # "Missing type annotation for 'self' in method"
    "D203",     # "Required one blank line before class docstrings" (incompatible with D211)
    "D213",     # "Required initial triple quotes to be on separate line for multiline docstrings."
    "S105",     # "Possible hardcoded password assigned" (too many false positives)
]
fixable = ["ALL"]
line-length = 88
format = "grouped"

[tool.ruff.per-file-ignores]
"tests/*" = [
    "S101",     # "Use of assert detected" (should be allowed in tests)
    "ANN001",   # "Missing type annotation for function argument" (fixtures' types are often complex, not worth it)
    "ANN201",   # "Missing return type annotation for function" (tests will always return None, there's no point)
]
