# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push to main and pull request to dev.
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains currently two jobs: linters and unit tests.

  linters:
    name: Linting and static analysis
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install dependencies needed for the other actions
      - name: Install dependencies
        run: python -m pip install -r tests/test_requirements.txt

      - name: Run Black
        run: black ./source ./tests --check

      - name: Run isort
        run: isort ./source ./tests --check

      - name: Check requirements order
        run: sort-requirements ./tests/test_requirements.txt --check

      - name: Run flake8
        run: flake8 ./source ./tests

      - name: Run MyPy
        run: mypy ./source ./tests


  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: linters

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install dependencies needed for the other actions
      - name: Install dependencies
        run: python -m pip install -r tests/test_requirements.txt

      - name: Run pytest
        run: pytest ./tests/unit_tests
