# This is a basic workflow to help you get started with Actions

name: Dev_deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push to dev.
  push:
    branches: [ "dev" ]


jobs:

  docker_build_and_push:
    runs-on: ubuntu-latest

    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.FILIP_DOCKERHUB_USERNAME }}
          password: ${{ secrets.FILIP_DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: honkou/towns_herald:dev


  ssh_trigger:
    runs-on: ubuntu-latest
    needs: docker_build_and_push

    steps:

      - name: Run_ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.FILIP_SERVER_IP}}
          username: ${{secrets.FILIP_SERVER_LOGIN}}
          password: ${{secrets.FILIP_SERVER_PASSWORD}}
          script: |
            cd ${{secrets.FILIP_DEV_TRIGGER_SCRIPT_PATH}}
            ./deploy_test_server.sh
